### ISSUE TITLE
Need for a contribution.md file 

### ISSUE THREAD

**Issue by deveshio** [Aditya61101/Group-Study#1]
As your projects don't contain the contribution.md file
it is getting difficult to get an understanding
I know the steps are provided in readMe.md file
but it is still better to have a contribution.md file instead of putting the steps in the readme. MD

keeping readme file for understand what the project is
keeping contribution file for contributior's guide

**Comment by deveshio** [comment]
I'd like to solve this issue

**Comment by Aditya61101** [comment]
> I'd like to solve this issue 
> 
> 
> 

Hi @Devesh-Daku ,  please see the repository again, I have added the contribution.md now.

**Comment by Aditya61101** [comment]
@Devesh-Daku I'm closing this issue for now.
