### ISSUE TITLE
Study Planner Logo

### ISSUE THREAD

**Issue by aindree-2005** [Aditya61101/Group-Study#11]
Generally, every product / website has a really eye catching logo. Study Planner could lack proper promotion due to absence of a logo. I intend to use Adobe Illustrator to create an intricate logo for the website. If that's something you believe the website could benefit from, I would love to work on this issue

**Comment by Aditya61101** [comment]
> Generally, every product / website has a really eye catching logo. Study Planner could lack proper promotion due to absence of a logo. I intend to use Adobe Illustrator to create an intricate logo for the website. If that's something you believe the website could benefit from, I would love to work on this issue

Cool go ahead!

**Comment by aindree-2005** [comment]
![study planner logo](https://github.com/Aditya61101/Group-Study/assets/68018372/ede6b703-5911-47dd-8524-d7f332c4fd43)
Logo on transparent background. Is this ok?

**Comment by aindree-2005** [comment]
![study planner light logo](https://github.com/Aditya61101/Group-Study/assets/68018372/13f57fc6-e2c3-4f0d-8484-6d0dbc961943)
Logo on transparent background. Light version

**Comment by Aditya61101** [comment]
Where are you planning to use this? @aindree-2005

**Comment by aindree-2005** [comment]
@Aditya61101 I was planning to use it in navbar. I created 2 versions, which can be used depending on background of pages in case it needs to be reused

**Comment by Aditya61101** [comment]
@aindree-2005  okay please implement it on navbar as well as an icon on tab.

**Comment by Aditya61101** [comment]
@aindree-2005  okay please implement it on navbar as well as an icon on tab.

**Comment by aindree-2005** [comment]
> @aindree-2005 okay please implement it on navbar as well as an icon on tab.

Got it! I'll also add folder of light and dark version of logos in both png and svg forms. No more changes are needed in the logo right?

**Comment by Aditya61101** [comment]
> > @aindree-2005 okay please implement it on navbar as well as an icon on tab.
> 
> Got it! I'll also add folder of light and dark version of logos in both png and svg forms. No more changes are needed in the logo right?

logo looks great! but ig you should also have to add .ico file.

**Comment by aindree-2005** [comment]
Oh ok will add .ico file as well!

**Comment by Aditya61101** [comment]
> Oh ok will add .ico file as well!

Pls implement it as well. I mean not only add those files use it on navbar and on tab. Also provide a screenshot with PR.
