### ISSUE TITLE
feat : implement confirm password in sign up form for validation.

### ISSUE THREAD

**Issue by NandishM0618** [Aditya61101/Group-Study#12]

**Comment by Aditya61101** [comment]
Assigned to @NandishM0618

**Comment by NandishM0618** [comment]
I have implemented the confirm password validator but after logging in its not showing the upcoming sessions is it due the "next public basename" or other .env variables.
![issue25](https://github.com/Aditya61101/Group-Study/assets/100901899/e05f0e0e-b4cc-45ad-9cd5-5dd048ef2e38)
![issue26](https://github.com/Aditya61101/Group-Study/assets/100901899/60a9babc-bda6-42e2-b857-8f773213c8f5)
as you can see the URL is pointing to upcoming sessions but not showing clarify me.

**Comment by Aditya61101** [comment]
> I have implemented the confirm password validator but after logging in its not showing the upcoming sessions is it due the "next public basename" or other .env variables.
> ![issue25](https://github.com/Aditya61101/Group-Study/assets/100901899/e05f0e0e-b4cc-45ad-9cd5-5dd048ef2e38)
> ![issue26](https://github.com/Aditya61101/Group-Study/assets/100901899/60a9babc-bda6-42e2-b857-8f773213c8f5)
> as you can see the URL is pointing to upcoming sessions but not showing clarify me.
>  

MONGO_URI = mongodb+srv://aditya:3d27SWJC8PQkotre@groupstudycluster.pnnisly.mongodb.net/GroupStudy?retryWrites=true&w=majority
password = 3d27SWJC8PQkotre
NEXT_PUBLIC_BASENAME = http://localhost:3000/
NEXTAUTH_URL = http://localhost:3000/
NEXTAUTH_SECRET = 4ch@n2215

i have provided the .env.local file details. Create a .env.local file at the root and paste these in it.

**Comment by NandishM0618** [comment]
@Aditya61101  done its working fine can i make pull request or you want any screenshots?

**Comment by Aditya61101** [comment]
> @Aditya61101  done its working fine can i make pull request or you want any screenshots?

Make a PR along with ss

**Comment by NandishM0618** [comment]
@Aditya61101 I have made pull request please review it #16 if any changes required please update me.
