### ISSUE TITLE
fix: Fix mobile view of SignUp/Login/Create New Session page 

### ISSUE THREAD

**Issue by SamIsTheFBI** [Aditya61101/Group-Study#14]
## :question:  Problem description

- Forms are not responsive and are distorted in mobile view, making it not so user-friendly.

## :camera:  Screenshot

| Mobile View |
|---|
|![Screenshot_2023-12-11-08-38-05-225_com android chrome](https://github.com/Aditya61101/Group-Study/assets/70562711/dcb82f15-d54a-4efe-8a28-791de9968388)|

## :framed_picture:  Proposed Solution

 - I wish to improve the responsiveness using Bootstrap and packages already used in the project. I can give the forms a more modern and appealing look for better user experience. 
 
## :page_with_curl:  Are you contributing for a program?

- I wish to contribute under <kbd> **CodePeak '23** </kbd>

Please do consider assigning me this task.

**Comment by Aditya61101** [comment]
assigned to @SamIsTheFBI . Pls fix the responsiveness of every page.

**Comment by SamIsTheFBI** [comment]
Hey @Aditya61101 

Would it be okay to change labels for some fields? 

Like the **Subject** field, it acts more like a short description of the session. So I could change it to **Description** instead.

Please do express your views on this.
