### ISSUE TITLE
style: Add styles to Landing page

### ISSUE THREAD

**Issue by SamIsTheFBI** [Aditya61101/Group-Study#17]
## :question:  Problem description

- The current landing page looks very basic

## :framed_picture:  Proposed Solution

 - I wish to make a new landing page which is visually appealing and describes the working of the web app with proper images. This contributes towards a better user experience. 
 
## :page_with_curl:  Are you contributing for a program?

- I wish to contribute under <kbd> **CodePeak '23** </kbd>

Please do consider assigning me this task.

**Comment by Aditya61101** [comment]
> ## :question:  Problem description
> 
> - The current landing page looks very basic
> 
> ## :framed_picture:  Proposed Solution
> 
>  - I wish to make a new landing page which is visually appealing and describes the working of the web app with proper images. This contributes towards a better user experience. 
>  
> ## :page_with_curl:  Are you contributing for a program?
> 
> - I wish to contribute under <kbd> **CodePeak '23** </kbd>
> 
> Please do consider assigning me this task.

Can u give some designs that you are going to implement before I assign this issue to you?

**Comment by SamIsTheFBI** [comment]
Ok I will send it here soon

**Comment by SamIsTheFBI** [comment]
Hey @Aditya61101 

This is the design I have prepared


https://github.com/Aditya61101/Group-Study/assets/70562711/e9c7831e-4660-4a29-ad50-9fdd44b79846

**Comment by Aditya61101** [comment]
Excellent ✨️, in small devices the svgs can be displayed a bit smaller.

**Comment by SamIsTheFBI** [comment]
Okay got it!

**Comment by SamIsTheFBI** [comment]
![image](https://github.com/Aditya61101/Group-Study/assets/70562711/fd3d6439-f7fc-4a41-bcea-85a449711bd5)

Is this be fine? @Aditya61101

**Comment by Aditya61101** [comment]
The images as well @SamIsTheFBI

**Comment by SamIsTheFBI** [comment]
Okay. Can I be assigned for this issue?

**Comment by Aditya61101** [comment]
> Okay. Can I be assigned for this issue?

are you showing those create and join session even for not logged in people? @SamIsTheFBI

**Comment by Aditya61101** [comment]
![Screenshot_20231214_015119_Chrome.jpg](https://github.com/Aditya61101/Group-Study/assets/75529750/2efd0261-946a-423c-883b-8ec4495a21d2)

Make these fonts a bit smaller for smaller devices. @SamIsTheFBI

**Comment by SamIsTheFBI** [comment]
@Aditya61101 done with #23

**Comment by Aditya61101** [comment]
> @Aditya61101 done with #23 

Yeah closing this and assigning you the points!
