### ISSUE TITLE
Modification of Navbar

### ISSUE THREAD

**Issue by aindree-2005** [Aditya61101/Group-Study#2]
Adding the following options to Navbar:

- [x]  Drop Down Menu

- [x]  Past Sessions Tab

- [ ] Search Bar

- [ ] Study Group Creation Tab , with dropdown for Grouping by subject, coding groups, and other hobby groups

**Comment by aindree-2005** [comment]
@Aditya61101 I would like to work on this issue

**Comment by Aditya61101** [comment]
> @Aditya61101 I would like to work on this issue

Assigned to you @aindree-2005

**Comment by Aditya61101** [comment]
@aindree-2005 I have updated the repo with a contribution.md file, please check that out before working on this issue.

**Comment by aindree-2005** [comment]
@Aditya61101  https://codepen.io/Aindree-Chatterjee/pen/bGzZWgP
Is this design for navbar ok?

**Comment by aindree-2005** [comment]
I will start with making changes to the original code after this design is approved

**Comment by Aditya61101** [comment]
> @Aditya61101 https://codepen.io/Aindree-Chatterjee/pen/bGzZWgP Is this design for navbar ok?

i guess the hamburger should only be shown on small devices.

**Comment by Aditya61101** [comment]
@aindree-2005 Before accepting the pull request, I will like to see some screenshots or a demo video of the navbar.

**Comment by aindree-2005** [comment]
![Screenshot (218)](https://github.com/Aditya61101/Group-Study/assets/68018372/1f54ef60-bdc2-48b8-a37c-df88c847058d)

I have not made the major changes that I did in the codepen one. I was finding it difficult to integrate that with the functionality. This is the dropdown for login/signup. I have added the same option in Create sessions tab

**Comment by Aditya61101** [comment]
> ![Screenshot (218)](https://github.com/Aditya61101/Group-Study/assets/68018372/1f54ef60-bdc2-48b8-a37c-df88c847058d)
> 
> I have not made the major changes that I did in the codepen one. I was finding it difficult to integrate that with the functionality. This is the dropdown for login/signup. I have added the same option in Create sessions tab

From the landing page how the user will go to create session or upcoming session page if only login and signup drop-down is there?

**Comment by aindree-2005** [comment]
In the original code, when we were logging in we could see the create session file. Should the Create session be included on the landing page too?

**Comment by Aditya61101** [comment]
> In the original code, when we were logging in we could see the create session file. Should the Create session be included on the landing page too?

Nah I mean after login, user should see those options right?

**Comment by aindree-2005** [comment]
![Screenshot (219)](https://github.com/Aditya61101/Group-Study/assets/68018372/9744eee1-2b11-4267-ae93-59b8c29316e3)
When I am trying to login after I click on localhost:3000. I am getting this error right from the start. I installed mongodb and after npm run dev I still keep getting this error

**Comment by Aditya61101** [comment]
> ![Screenshot (219)](https://private-user-images.githubusercontent.com/68018372/289261260-9744eee1-2b11-4267-ae93-59b8c29316e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTQ5NzIsIm5iZiI6MTcwMjExNDY3MiwicGF0aCI6Ii82ODAxODM3Mi8yODkyNjEyNjAtOTc0NGVlZTEtMmIxMS00MjY3LWFlOTMtNTliOGMyOTMxNmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA5Mzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MjZhYjYyYmE5ODhkZTg0NWU2MTdjYjZkNDlkNTZlZWQzMWIzZDgxYWI4YThhN2EwZjQ1NWIxM2M0MDZiYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nnGPAjXXlFNbjiC67wSDwBP43wQ4OCoOJ4KKW648FwE) When I am trying to login after I click on localhost:3000. I am getting this error right from the start. I installed mongodb and after npm run dev I still keep getting this error

have checked the console or the terminal?

**Comment by Aditya61101** [comment]
![Screenshot 2023-12-09 151738](https://github.com/Aditya61101/Group-Study/assets/75529750/837cfac8-c954-4590-9511-5f4905e2b23d)
I am able to navigate to the login page, for mongodb, I have given the network access to all.

**Comment by aindree-2005** [comment]
![Screenshot (221)](https://github.com/Aditya61101/Group-Study/assets/68018372/2cb35c42-5991-4b11-8c7d-f70f4eab47b6)
Yes I am getting this error in terminal

**Comment by Aditya61101** [comment]
> ![Screenshot (221)](https://private-user-images.githubusercontent.com/68018372/289263561-2cb35c42-5991-4b11-8c7d-f70f4eab47b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTYwODMsIm5iZiI6MTcwMjExNTc4MywicGF0aCI6Ii82ODAxODM3Mi8yODkyNjM1NjEtMmNiMzVjNDItNTk5MS00YjExLThjN2QtZjcwZjRlYWI0N2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA5NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MGExNTA3MzY4ZDE3ZTg0NTM2ZWFjZjM1ZmE5NTYzYzBiMTMxODg3OGI5ZTI5YmMxZTU2MDJhY2YxOWJlODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dp6SZmmLutTX7EusOy6F3WuleF4XWMOo9GRlWvADd4) Yes I am getting this error in terminal

this means you are not able to access the mongodb database w.r.t this project :/
Although I have allowed connection from everywhere

**Comment by aindree-2005** [comment]
Oh ok. How do I fix this then? I am unable to show the preview of the changes made

**Comment by Aditya61101** [comment]
> Oh ok. How do I fix this then? I am unable to show the preview of the changes made

you need to have the .env.local file with you. I'm giving you the details of the file.

MONGO_URI = mongodb+srv://aditya:3d27SWJC8PQkotre@groupstudycluster.pnnisly.mongodb.net/GroupStudy?retryWrites=true&w=majority
password = 3d27SWJC8PQkotre
NEXT_PUBLIC_BASENAME = http://localhost:3000/
NEXTAUTH_URL = http://localhost:3000/
NEXTAUTH_SECRET = 4ch@n2215

create a .env.local file in the root and paste the above details. It should start working.

**Comment by aindree-2005** [comment]
![Screenshot (222)](https://github.com/Aditya61101/Group-Study/assets/68018372/745640b4-7442-4866-83dc-9929caad54b6)
This is the current design. For coding sessions , past sessions and others separate tabs have been added to sort out and refer back to past sessions

**Comment by Aditya61101** [comment]
> ![Screenshot (222)](https://private-user-images.githubusercontent.com/68018372/289274457-745640b4-7442-4866-83dc-9929caad54b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjk0OTgsIm5iZiI6MTcwMjEyOTE5OCwicGF0aCI6Ii82ODAxODM3Mi8yODkyNzQ0NTctNzQ1NjQwYjQtNzQ0Mi00ODY2LTgzZGMtOTkyOWNhYWQ1NGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEzMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZGY3MWQxZWM1MWE0MzBmNTMzM2Q3NjljYjRhMTQyZDkwZmNlZDFkNGJjMjdlY2I3NjhiYWY0NzVkYjY5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_dpczX0kpLdE_6_6wRZehMV1-ThAryA6rNnK08p50A) This is the current design. For coding sessions , past sessions and others separate tabs have been added to sort out and refer back to past sessions

What should be on the past sessions page? Also, what's the need for coding sessions? We haven't distinguished between sessions yet.

**Comment by aindree-2005** [comment]
> > ![Screenshot (222)](https://private-user-images.githubusercontent.com/68018372/289274457-745640b4-7442-4866-83dc-9929caad54b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjk0OTgsIm5iZiI6MTcwMjEyOTE5OCwicGF0aCI6Ii82ODAxODM3Mi8yODkyNzQ0NTctNzQ1NjQwYjQtNzQ0Mi00ODY2LTgzZGMtOTkyOWNhYWQ1NGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEzMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZGY3MWQxZWM1MWE0MzBmNTMzM2Q3NjljYjRhMTQyZDkwZmNlZDFkNGJjMjdlY2I3NjhiYWY0NzVkYjY5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_dpczX0kpLdE_6_6wRZehMV1-ThAryA6rNnK08p50A) This is the current design. For coding sessions , past sessions and others separate tabs have been added to sort out and refer back to past sessions
> 
> What should be on the past sessions page? Also, what's the need for coding sessions? We haven't distinguished between sessions yet.


That page hasn't been made yet. Study sessions that have gone by can be recorded on there. Kind of similar to past orders/past rides in Swiggy and Uber. 
As for the 2nd case, should I remove coding sessions and others?
Actually it was in the issue, that's why I added it

**Comment by Aditya61101** [comment]
> > > ![Screenshot (222)](https://private-user-images.githubusercontent.com/68018372/289274457-745640b4-7442-4866-83dc-9929caad54b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjk0OTgsIm5iZiI6MTcwMjEyOTE5OCwicGF0aCI6Ii82ODAxODM3Mi8yODkyNzQ0NTctNzQ1NjQwYjQtNzQ0Mi00ODY2LTgzZGMtOTkyOWNhYWQ1NGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEzMzk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZGY3MWQxZWM1MWE0MzBmNTMzM2Q3NjljYjRhMTQyZDkwZmNlZDFkNGJjMjdlY2I3NjhiYWY0NzVkYjY5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_dpczX0kpLdE_6_6wRZehMV1-ThAryA6rNnK08p50A) This is the current design. For coding sessions , past sessions and others separate tabs have been added to sort out and refer back to past sessions
> > 
> > 
> > What should be on the past sessions page? Also, what's the need for coding sessions? We haven't distinguished between sessions yet.
> 
> That page hasn't been made yet. Study sessions that have gone by can be recorded on there. Kind of similar to past orders/past rides in Swiggy and Uber. As for the 2nd case, should I remove coding sessions and others? Actually it was in the issue, that's why I added it

better to remove coding sessions and others, as till now we haven't distinguished between courses. regarding past sessions, if you can make a past session page that will also work.

**Comment by aindree-2005** [comment]
Got it. I'll create a separate issue for that then?

**Comment by aindree-2005** [comment]
Made the changes. And created a blank index.js for past sessions

**Comment by Aditya61101** [comment]
> Got it. I'll create a separate issue for that then?

Better to implement it in this issue only. Just change the issue name

**Comment by aindree-2005** [comment]
> > Got it. I'll create a separate issue for that then?
> 
> Better to implement it in this issue only. Just change the issue name

I am not well versed in JS enough to create the reusable PastSession components. So it would be better if I could learn the required things and come back to it or if someone else could do the reusable components. Otherwise it would be great if I could get some hints

**Comment by Aditya61101** [comment]
> > > Got it. I'll create a separate issue for that then?
> > 
> > Better to implement it in this issue only. Just change the issue name
> 
> I am not well versed in JS enough to create the reusable PastSession components. So it would be better if I could learn the required things and come back to it or if someone else could do the reusable components. Otherwise it would be great if I could get some hints
> 

Okay no issue, you also thought to implement search bar feature on navbar, right?

**Comment by aindree-2005** [comment]
> > > > Got it. I'll create a separate issue for that then?
> > > 
> > > 
> > > Better to implement it in this issue only. Just change the issue name
> > 
> > 
> > I am not well versed in JS enough to create the reusable PastSession components. So it would be better if I could learn the required things and come back to it or if someone else could do the reusable components. Otherwise it would be great if I could get some hints
> 
> Okay no issue, you also thought to implement search bar feature on navbar, right?

Yeah I wanted to add search bar but I wasn't sure if it would be too useful in this project since people could go back and look at their past and upcoming sessions in separate tabs

**Comment by Aditya61101** [comment]
> > > > > Got it. I'll create a separate issue for that then?
> > > > 
> > > > 
> > > > Better to implement it in this issue only. Just change the issue name
> > > 
> > > 
> > > I am not well versed in JS enough to create the reusable PastSession components. So it would be better if I could learn the required things and come back to it or if someone else could do the reusable components. Otherwise it would be great if I could get some hints
> > 
> > Okay no issue, you also thought to implement search bar feature on navbar, right?
> 
> Yeah I wanted to add search bar but I wasn't sure if it would be too useful in this project since people could go back and look at their past and upcoming sessions in separate tabs
> 

Please give a final demo of all the things that you have done, before I merge the PR.

**Comment by aindree-2005** [comment]
![Screenshot (218)](https://github.com/Aditya61101/Group-Study/assets/68018372/bcc7d7f4-55e5-499e-b415-6ed94a7eb98c)
![Screenshot (233)](https://github.com/Aditya61101/Group-Study/assets/68018372/d960875a-ad8f-4ea5-b2cb-762bc5f2e885)

Final demo @Aditya61101

**Comment by Aditya61101** [comment]
> ![Screenshot (218)](https://github.com/Aditya61101/Group-Study/assets/68018372/bcc7d7f4-55e5-499e-b415-6ed94a7eb98c)
> ![Screenshot (233)](https://github.com/Aditya61101/Group-Study/assets/68018372/d960875a-ad8f-4ea5-b2cb-762bc5f2e885)
> 
> Final demo @Aditya61101 

Okay merged you pull request!
