### ISSUE TITLE
Creating a standalone software for the App (Browser Install Popup)

### ISSUE THREAD

**Issue by pooranjoyb** [Aditya61101/Group-Study#20]
### Things I wanna Implement : 

- [x] Create a Service Worker for the Applicaiton
- [x] Register the service worker in the Browsers
- [x] Adding a detailed `manifest.json` file to let the browers know about the Application
- [x] Popup to install the `Standalone App` in the desktop as an application
- [x] Popup to install the `Standalone App` in the mobile as an Browser Shortcut/`.apk`

I wanna take up this under CODEPEAK 2023 @Aditya61101

**Comment by Aditya61101** [comment]
Go ahead @pooranjoyb 🔥

**Comment by pooranjoyb** [comment]
Hey @Aditya61101 which logo do you want the App to use, the previous violet-blue one or the new white Study-Planner one ?

**Comment by Aditya61101** [comment]
> Hey @Aditya61101 which logo do you want the App to use, the previous violet-blue one or the new white Study-Planner one ? 

The new one
