### ISSUE TITLE
centering the `don't have  an account` text on the login page

### ISSUE THREAD

**Issue by Not-Sarthak** [Aditya61101/Group-Study#26]
![image](https://github.com/Aditya61101/Group-Study/assets/92942966/420594af-a211-43cb-8cb1-23e3951d9597)
The text should be centered to improve the ui

**Comment by Aditya61101** [comment]
No @Not-Sarthak ig the positioning is correct.

**Comment by Not-Sarthak** [comment]
ik that was a v small and irrelevant issue but somehow my eyes got caught there and thought of mentioning it over here

**Comment by Aditya61101** [comment]
Closing this issue @Not-Sarthak
