### ISSUE TITLE
Modern Suitable logo

### ISSUE THREAD

**Issue by AaadityaG** [Aditya61101/Group-Study#28]
Participating in Codepeak

**Comment by Aditya61101** [comment]
It's good that you are participating in codepeak, @AaadityaG . But before assigning, I would like to see the logo that u want to add to the website.

**Comment by AaadityaG** [comment]
@Aditya61101 Consider these logos
 https://www.canva.com/design/DAF3owmxvCY/mNuHAY8Vn3xOSI8EXtsm5g/edit?utm_content=DAF3owmxvCY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

You have an edit access, choose any one of them..
