### ISSUE TITLE
Create a user profile page

### ISSUE THREAD

**Issue by Aditya61101** [Aditya61101/Group-Study#3]
You have to create a user profile page for this website. To achieve this, you can change the backend as well as the frontend without changing the current state of the website. The page should be accessible via all the private routes only.

The UI should match the current website's UI.

**Comment by pooranjoyb** [comment]
Assign me this issue usder codepeak'23 :)
Will try to submit a PR by tomorrow midnight!

@Aditya61101

**Comment by Aditya61101** [comment]
> Assign me this issue usder codepeak'23 :)
> Will try to submit a PR by tomorrow midnight!
> 
> @Aditya61101 

Assigned this to @pooranjoyb . Before working, make sure that you have gone through contribution.md file

**Comment by pooranjoyb** [comment]
Hey @Aditya61101 it is possible to access the DB to login, as for the development stage there should a common username and passwords for testing. You can either provide me one or can share the DB credentials (if exists).

**Comment by Aditya61101** [comment]
> Hey @Aditya61101 it is possible to access the DB to login, as for the development stage there should a common username and passwords for testing. You can either provide me one or can share the DB credentials (if exists).

MONGO_URI = mongodb+srv://aditya:3d27SWJC8PQkotre@groupstudycluster.pnnisly.mongodb.net/GroupStudy?retryWrites=true&w=majority
password = 3d27SWJC8PQkotre
NEXT_PUBLIC_BASENAME = http://localhost:3000/
NEXTAUTH_URL = http://localhost:3000/
NEXTAUTH_SECRET = 4ch@n2215

i have provided the .env.local file details. Create a .env.local file at the root and paste these in it.

**Comment by Aditya61101** [comment]
@pooranjoyb  Before accepting the pull request, I would like to see some screenshots or a demo video of the work that you have done.

**Comment by pooranjoyb** [comment]
> @pooranjoyb  Before accepting the pull request, I would like to see some screenshots or a demo video of the work that you have done.

Already added. Check PRs

**Comment by Aditya61101** [comment]
> > @pooranjoyb  Before accepting the pull request, I would like to see some screenshots or a demo video of the work that you have done.
> 
> Already added. Check PRs

yup checked and merged your PR!!

**Comment by pooranjoyb** [comment]
> > > @pooranjoyb  Before accepting the pull request, I would like to see some screenshots or a demo video of the work that you have done.
> > 
> > 
> > Already added. Check PRs
> 
> yup checked and merged your PR!!

Thanks @Aditya61101 
Please label it under `Codepeak2023`

**Comment by Aditya61101** [comment]
> > > > @pooranjoyb  Before accepting the pull request, I would like to see some screenshots or a demo video of the work that you have done.
> > > 
> > > 
> > > Already added. Check PRs
> > 
> > 
> > yup checked and merged your PR!!
> 
> Thanks @Aditya61101 Please label it under `Codepeak2023`

I have labeled it under codepeak'23, as per the points assignment doc.

**Comment by Aditya61101** [comment]
@pooranjoyb awarded you 20 points for solving this issue 🎉

**Comment by Aditya61101** [comment]
hey @pooranjoyb , you don't to hard code the user profile values; whatever you are getting from the backend or user session, just show them. Please show the real number of sessions created and registered instead of hard-coding it. It's a hard issue so you have to do these things in order to get full 20 points.

**Comment by pooranjoyb** [comment]
Sure @Aditya61101 I agree, 
But it would be more useful if we increase the fields while `Registering a User` 
Like taking the `Name`, `Age`, `Address`, etc, coz as of now the fields are really less in the DB to be shown in the Profile Section. Lemme know your views on this :)

Otherwise I shall go on as mentioned. 
@Aditya61101

**Comment by Aditya61101** [comment]
> Sure @Aditya61101 I agree, 
> But it would be more useful if we increase the fields while `Registering a User` 
> Like taking the `Name`, `Age`, `Address`, etc, coz as of now the fields are really less in the DB to be shown in the Profile Section. Lemme know your views on this :)
> 
> Otherwise I shall go on as mentioned. 
> @Aditya61101 

Yeah sure go ahead but you need to handle the case for already registered people also. Also show real no. Of sessions created and registered.

**Comment by pooranjoyb** [comment]
Sure thing! @Aditya61101 :)

**Comment by Aditya61101** [comment]
> Sure thing! @Aditya61101 :)
> 

Weren't you able to fetch data about number of sessions created and registered for a user? @pooranjoyb

**Comment by Aditya61101** [comment]
![Screenshot_20231210_161804_Chrome.jpg](https://github.com/Aditya61101/Group-Study/assets/75529750/57013285-ca9f-482e-a2be-f8987db45c92)

Please make it mobile responsive as well. @pooranjoyb

**Comment by pooranjoyb** [comment]
> > Sure thing! @Aditya61101 :)
> 
> Weren't you able to fetch data about number of sessions created and registered for a user? @pooranjoyb

Okay I'll do the required changes and let you know. 
Also, will I get some extra points after this is merged? Asking coz the initial issue didn't have these all features. :) @Aditya61101

**Comment by Aditya61101** [comment]
> > > Sure thing! @Aditya61101 :)
> > 
> > Weren't you able to fetch data about number of sessions created and registered for a user? @pooranjoyb
> 
> Okay I'll do the required changes and let you know. 
> Also, will I get some extra points after this is merged? Asking coz the initial issue didn't have these all features. :) @Aditya61101 

I guess, it's already assigned as a hard issue, and I expected to have at least these fields shown on user profile. So 20 points are enough tbh.

**Comment by pooranjoyb** [comment]
Please check the PR. I've made the requested changes :) @Aditya61101

**Comment by Aditya61101** [comment]
> Please check the PR. I've made the requested changes :) @Aditya61101

i only need the number of sessions registered and created to be displayed on the card of the profile page. @pooranjoyb 
![Screenshot 2023-12-10 183232](https://github.com/Aditya61101/Group-Study/assets/75529750/106db266-e04e-4876-ba64-ae5d326f5aa2)

**Comment by Aditya61101** [comment]
Done @pooranjoyb ?

**Comment by pooranjoyb** [comment]
Dropping the PR right away, I was busy for some while. @Aditya61101
