### ISSUE TITLE
Add Button 'Go to Home' on 404 page

### ISSUE THREAD

**Issue by AaadityaG** [Aditya61101/Group-Study#30]
![404_ This page could not be found - Google Chrome 21-12-2023 01_12_49 PM](https://github.com/Aditya61101/Group-Study/assets/114663382/d62f2574-a75a-4a3e-837c-911981bf6c27)

**I am participating in Codepeak**

**Comment by Tanishka023** [comment]
Hey @Aditya61101 , Can you please assign this to me??

**Comment by AaadityaG** [comment]
@Tanishka023 Ok you can do it!

**Comment by Tanishka023** [comment]
@AaadityaG When does this "404. The Page could not be found" screen appears ? Can you please elaborate about this because the things look fine to me here.

**Comment by AaadityaG** [comment]
> @AaadityaG When does this "404. The Page could not be found" screen appears ? Can you please elaborate about this because the things look fine to me here.

https://group-study.vercel.app/adfsfsd

Also at https://group-study.vercel.app/upcoming-sessions/saasd

**Comment by Tanishka023** [comment]
Okay!

**Comment by Aditya61101** [comment]
Yeah, a 404 page appears whenever we try to access a non existing page. But ig through navbar we can go to the home screen, isn't it @AaadityaG @Tanishka023?

**Comment by AaadityaG** [comment]
Yeah I thought of it later...😅😂

**Comment by Tanishka023** [comment]
So what should I do now? @Aditya61101 @AaadityaG

**Comment by Aditya61101** [comment]
yeah so i don't think we need a separate button for this, right? @AaadityaG @Tanishka023

**Comment by Tanishka023** [comment]
Yeah I think everything looks fine here @Aditya61101 @AaadityaG

**Comment by AaadityaG** [comment]
Yeah same, cause if we want to add button we also need to recreate whole 404 page

**Comment by Aditya61101** [comment]
Yup so I'm closing this issue
