### ISSUE TITLE
Login SignUp button redesign desktop,mobile

### ISSUE THREAD

**Issue by Dhaneshwar7** [Aditya61101/Group-Study#31]
I can Re-design Login /SignUP button Desktop view as well as Responsive. 
In click it will looks good. Assign me want to contribute ...

<img width="883" alt="Screenshot 2023-12-24 at 12 40 54 AM" src="https://github.com/Aditya61101/Group-Study/assets/87529812/6ed75934-5cd0-48a8-a032-ccc3865ec30b">
<img width="365" alt="Screenshot 2023-12-24 at 12 41 10 AM" src="https://github.com/Aditya61101/Group-Study/assets/87529812/f957b0a7-fc96-4bf1-a96f-958e2ea09ac9">

**Comment by Aditya61101** [comment]
Hi @Dhaneshwar7 , before assigning I would like to see the design that u want to implement.

**Comment by Dhaneshwar7** [comment]
> Hi @Dhaneshwar7 , before assigning I would like to see the design that u want to implement.

Okay

**Comment by Dhaneshwar7** [comment]
@Aditya61101  Hey,,  Check this design  assign me so i can code....
I know this not very hard issue but i am new in contributions i just want start with this....


https://github.com/Aditya61101/Group-Study/assets/87529812/7b7aa051-c9f9-4862-bebf-f10aabcb9c04
