### ISSUE TITLE
Feat: Dark Mode and Light Mode Feature 

### ISSUE THREAD

**Issue by Mayank77maruti** [Aditya61101/Group-Study#4]
I would like to implement the dark mode and light mode feature to the website , that would make the website more visually appealing.
Please do assign this task to me under codepeak'23 tag.

**Comment by Aditya61101** [comment]
> I would like to implement the dark mode and light mode feature to the website , that would make the website more visually appealing.
> Please do assign this task to me under codepeak'23 tag.

Assigned this to @Mayank77maruti . Please go through contribution.md before working.

**Comment by Albert-2** [comment]
@Aditya61101
I would love to contribute to this feature. 
As I am quite good at frontend so can you please assign me this issue if @Mayank77maruti is not working
THANK YOU FOR CONSIDERING....... :)

**Comment by Aditya61101** [comment]
Is it okay @Mayank77maruti if I assign this issue to @Albert-2 ?

**Comment by Mayank77maruti** [comment]
@Aditya61101 , it's ok.

**Comment by Aditya61101** [comment]
You can start working @Albert-2

**Comment by Albert-2** [comment]
![image](https://github.com/Aditya61101/Group-Study/assets/90373859/2a7c9fd0-6c3c-4208-9b05-86c8a8581d5e)

![image](https://github.com/Aditya61101/Group-Study/assets/90373859/9eea9db6-5a9c-400d-a49a-daf9ab350ffd)

can you please help me with this
i am trying to figure it out from last night

MONGO_URI = "mongodb://localhost:27017/GroupStudyApp"
NEXT_PUBLIC_BASENAME = "http://localhost:3000/"
NEXTAUTH_URL = 
NEXTAUTH_SECRET = "LightWeight"

**Comment by Aditya61101** [comment]
Correct credentials @Albert-2 

MONGO_URI = mongodb+srv://aditya:3d27SWJC8PQkotre@groupstudycluster.pnnisly.mongodb.net/GroupStudy?retryWrites=true&w=majority
password = 3d27SWJC8PQkotre
NEXT_PUBLIC_BASENAME = http://localhost:3000/
NEXTAUTH_URL = http://localhost:3000/
NEXTAUTH_SECRET = 4ch@n2215

i have provided the .env.local file details. Create a .env.local file at the root and paste these in it.

**Comment by Albert-2** [comment]
okok thank you very much
ssly appreciated.....!!

**Comment by Albert-2** [comment]
hey @Aditya61101 
First of all thank you for letting me contribute to this great project 
I've contributed dark mode but i guess the heights will cause some issue in ui hope you will co-operate
