### ISSUE TITLE
[FEATURE REQUEST] Show number of students registered to a session

### ISSUE THREAD

**Issue by SamIsTheFBI** [Aditya61101/Group-Study#5]
## :question:  Problem description

- Currently, the study sessions card only shows the maximum number of students allowed for a session and not the number of students currently registered for it. 
- Furthermore the register button is not disabled for users who have already registered the session.

## :camera:  Screenshot

![image](https://github.com/Aditya61101/Group-Study/assets/70562711/dc831513-9cda-45b5-a26a-3d36c488a67f)

## :framed_picture:  Proposed Solution

 - I wish to improve the UI/UX of the card by showing number of registered students and improving card design. I can work my way with Material UI to maintain a uniform look.

## :page_with_curl:  Are you contributing for a program?

- I wish to contribute under <kbd> **CodePeak '23** </kbd>

Please do consider assigning me this task.

**Comment by Aditya61101** [comment]
Hey, @SamIsTheFBI, can't you improve the design with Bootstrap itself?

**Comment by SamIsTheFBI** [comment]
Oh, right I can do so @Aditya61101.  My bad, I didn't notice it was Bootstrap!

Sure I can work with Bootstrap as long as the documentations are still there 😄

**Comment by Aditya61101** [comment]
> Oh, right I can do so @Aditya61101.  My bad, I didn't notice it was Bootstrap!
> 
> Sure I can work with Bootstrap as long as the documentations are still there 😄

Yeah then go ahead

**Comment by SamIsTheFBI** [comment]
Hey @Aditya61101 :wave: 

I have made a PR #10 regarding this feature. I have worked on the new design of session card and fixed some API calls for fetching certain data from database. I had to play around with backend to fetch the number of users registered to particular sessions & also for unregistering users.

The code contains no breaking changes. Please see to it & consider merging it under the label <kbd>CodePeak '23</kbd>.

**Comment by Aditya61101** [comment]
> Hey @Aditya61101 :wave: 
> 
> I have made a PR #10 regarding this feature. I have worked on the new design of session card and fixed some API calls for fetching certain data from database. I had to play around with backend to fetch the number of users registered to particular sessions & also for unregistering users.
> 
> The code contains no breaking changes. Please see to it & consider merging it under the label <kbd>CodePeak '23</kbd>.

Great job @SamIsTheFBI !
